<?php

// This file is automatically generated and modified by phpMyBackupPro v.2.1

$CONF['sql_user']="newidol";
$CONF['sql_passwd']="newidol";
$CONF['sql_host']="192.168.1.5";
$CONF['sql_db']="";
$CONF['ftp_use']="0";
$CONF['allow_dir_backup']="0";
$CONF['email_use']="0";
$CONF['sitename']="mySite";
$CONF['lang']="chinese";
$CONF['import_error']="1";
$CONF['no_login']="0";
$CONF['login']="0";
$CONF['dir_backup']="0";
$CONF['dir_rec']="1";
$CONF['email']="";
$CONF['ftp_pasv']="1";
$CONF['ftp_del']="1";
$CONF['ftp_server']="example.net";
$CONF['ftp_user']="";
$CONF['ftp_passwd']="";
$CONF['ftp_path']="example/";
$CONF['ftp_port']="21";
$CONF['date']="%x %H:%M";
$CONF['del_time']="7";
$CONF['del_number']="5";
$CONF['timelimit']="60";
$CONF['confirm']="1";
$CONF['stylesheet']="standard";

$PMBP_SYS_VAR['last_scheduled']="1253156475";
$PMBP_SYS_VAR['this_login']="2009/9/17 06:48 (IP: 127.0.0.1)";
$PMBP_SYS_VAR['last_login']="09/17/09 06:48 (IP: 127.0.0.1)";
$PMBP_SYS_VAR['dir_lists']="1";
$PMBP_SYS_VAR['memory_limit']="38000000";
$PMBP_SYS_VAR['except_tables']="";
$PMBP_SYS_VAR['scheduled_debug']="0";
$PMBP_SYS_VAR['schedule_all_dbs']="0";
$PMBP_SYS_VAR['ftp_timeout']="10";
$PMBP_SYS_VAR['dir_email_backup']="0";
$PMBP_SYS_VAR['F_dbs']="user_db";
$PMBP_SYS_VAR['F_comment']="";
$PMBP_SYS_VAR['F_tables']="on";
$PMBP_SYS_VAR['F_data']="on";
$PMBP_SYS_VAR['F_drop']="on";
$PMBP_SYS_VAR['F_compression']="";
$PMBP_SYS_VAR['F_ftp_dirs']="";
$PMBP_SYS_VAR['F_ftp_dirs_2']="";
$PMBP_SYS_VAR['F_packed']="";
$PMBP_SYS_VAR['F_updates']="1";
$PMBP_SYS_VAR['F_ffadd']="1";
$PMBP_SYS_VAR['EXS_scheduled_file']="mysql.php";
$PMBP_SYS_VAR['EXS_scheduled_dir']="../phpMyBackupPro/export/";
$PMBP_SYS_VAR['EXS_period']="/24";
$PMBP_SYS_VAR['security_key']="28af256dd0bc47981b3623bf410ac760";

?>